apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project8-nginx-rollout
# namespace set elsewhere; can only lead to conflict later
# namespace: project8-prod
spec:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 60
        - analysis:
            templates:
              - templateName: project9-restart-rollback-freeze-prod
                clusterScope: true
        - setWeight: 50
        - pause:
            duration: 120

