apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project8-nginx-rollout
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: 349821334974.dkr.ecr.us-east-1.amazonaws.com/project1-nginx:f875f5de2bbca28f0438693dc8343be45d0a99fc

